update to ruby 3.3 in dockerimage
[#186825639]

this image caontains an almost ancient version of ruby. We're hoping
for the best by bumping directly to 3.3. We're doing so because we cannot
run recent versions of bundler with 2.7 anymore.

fix:

```
ERROR:  Error installing bundler:
	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.3.183.
```

in docker image build