Chore/move to runway (#1127)
* runway: clean secrets

- rename anchors.

maru was a long lived env that doesn't exist anymore. these are just toolsmiths
envs.

- group and comment secrets

- replace references with anchors

* runway: use harbor images

avoid docker rate limitation

* make shuttle optional

using shuttle on runway needs special considerations. removing it
and relying on BOSH_ALL_PROXY and CREDHUB_PROXY. ssh'ing to the director
via it's private IP is solved via an `.ssh/config`. This seems to be the
only usecase shuttle solves.

* fix failing ci

fix:
```
ERROR: (gcloud.compute.firewall-rules.delete) The required property [project] is not currently set.
It can be set on a per-command basis by re-running your command with the [--project] flag.

You may set it for your current workspace by running:

  $ gcloud config set project VALUE
```

* increase timeouts

since moving to a shared CI these requests take longer to finish.

fixes:

```
  [FAILED] Timed out after 10.001s.
  Expected process to exit.  It did not.
  In [It] at: /tmp/build/f3c1b5a9/bosh-backup-and-restore/s3-config-validator/src/test/binary/binary_test.go:114 @ 09/25/23 14:50:58.055
```